# Generated by Django 5.0.1 on 2024-11-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_comment_post_blog_post_publish_bb7600_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='read_more',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='media_type',
            field=models.CharField(choices=[('IMG', 'Image'), ('VID', 'Video'), ('AUD', 'Audio'), ('YTV', 'Youtube video'), ('NON', 'None')], default='NON', max_length=3),
        ),
    ]
