# Generated by Django 5.0.1 on 2024-01-10 09:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_pricingplan_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('description_two', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='banner/')),
            ],
        ),
    ]
