# Generated by Django 5.0.1 on 2024-01-14 15:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_portfolio_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('bio', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='developers/')),
                ('facebook_url', models.URLField(blank=True)),
                ('telegram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
            ],
        ),
    ]
